name: CI

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:

  tests:
    name: Tests (PHP ${{ matrix.php }})
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: [ '5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0' ]
      fail-fast: false
    env:
      MATRIX_PHP: ${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "xdebug"
          php-version: "${{ matrix.php }}"
          tools: composer
          # PHP 7.1 development web server segfaults if timezone not set.
          ini-values: date.timezone=Europe/Paris, error_reporting=-1, display_errors=On

      - name: Configure for PHP >= 7.1
        if: "${{ matrix.php >= '7.1' }}"
        run: |
          composer require --no-update --dev symfony/error-handler "^4.4 || ^5.0"

      - name: Install dependencies
        run: |
          composer update --no-interaction --prefer-dist

      - name: Setup test web server
        run: |
          - php -S localhost:8000 -t $(pwd) > /dev/null 2> /tmp/webserver_output.txt &
          - export REPO_URL=http://localhost:8002/

      - name: Wait for browser & PHP to start
        run: |
          while ! nc -z localhost 8002 </dev/null; do echo Waiting for PHP server to start...; sleep 1; done

      - name: Run tests
        run: |
          vendor/bin/phpunit -v --coverage-clover=coverage.clover

      - name: Upload Coverage to Scrutinizer CI (PHP < 8.0)
        if: "${{ matrix.php < '8.0' }}"
        run: |
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --repository=g/chobie/jira-api-restclient --format=php-clover coverage.clover

      - name: Upload Coverage to Scrutinizer CI (PHP >= 8.0)
        if: "${{ matrix.php >= '8.0' }}"
        run: |
           composer require scrutinizer/ocular
           vendor/bin/ocular code-coverage:upload --repository=g/chobie/jira-api-restclient --format=php-clover coverage.clover
